---
# tasks to complete before running roles
- hosts: localhost
  gather_facts: yes
  connection: local
  become: true
  pre_tasks:
    - name: pre-run | update package cache (arch)
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

    - name: pre-run | update package cache (debian, etcs
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: localhost
  become: true
  roles:
    - workstation

## run roles
#- hosts: all
#  tags: base
#  become: true
#  roles:
#    - base
#    - other_roles
