- name: Install i3wm and dependencies
  package:
    name: i3-gaps
    name: xorg

- name: install ly-dm
  become_user: "{{ users[0] }}"
  command: "{{ item }}"
  with_items:
    - "yay -S ly --noconfirm"
    - "sudo systemctl enable ly.service"
