- name: install lydm dependencies
  package:
    - build-essential
    - libpam0g-dev
    - libxcb-xkb-dev

git clone https://github.com/nullgemm/ly.git

make github
make
sudo make install
sudo systemctl enable ly.service
