- name: check if grub exists
  stat:
    path: /etc/default/grub
  register: grub_installed

- name: check if grub theme is installed
  stat:
    path: /boot/grub/themes/CyberRe
  register: theme_installed

- name: Install i3wm and script dependencies
  package:
    name:
      - i3-gaps
      - xorg
      - imagemagick
      - xss-lock
      - i3lock
      - xautolock
      - libconfig
      - picom

# install ly login screen
- name: install ly-dm (arch)
  become_user: "{{ users[0] }}"
  command: "{{ item }}"
  with_items:
    - "yay -S ly-git --noconfirm"
    - "sudo systemctl enable ly.service"
  when: ansible_distribution == "Archlinux"

- name: install dependencies for ly-dm (debian)
  package:
    name:
      - build-essential
      - libpam0g-dev
      - libxcb-xkb-dev
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: install ly-dm (debian)
  command: "{{ item }}"
  with_items:
    - "git clone --recurse-submodules https://github.com/nullgemm/ly.git"
    - "cd ly"
    - "make"
    - "make install"
    - "systemctl enable ly.service"
    - "cd ..; rm -rf ly"
  when: ansible_distribution in ["Debian", "Ubuntu"]

# configure grub theme
- name: configure grub theme
  command: "{{ item }}"
  args:
    chdir: "/tmp"
  with_items:
    - "curl https://raw.githubusercontent.com/alealexpro100/various_files/master/Grub2-theme%20CyberRe%201.0.0.tar.gz -o CyberRe.tar.gz"
    - "tar -xf CyberRe.tar.gz"
    - "mv \"CyberRe 1.0.0/CyberRe/\" /boot/grub/themes"
    - "sed -i '/#GRUB_THEME=/c\\GRUB_THEME=\"/boot/grub/themes/CyberRe/theme.txt\"' /etc/default/grub"
    - "grub-mkconfig -o /boot/grub/grub.cfg"
    - "rm -rf CyberRe*"
  when: (grub_installed.stat.exists) and (theme_installed.stat.exists != true)

# setup wallpaper and lockscreen
- name: install corrupter for lock screen
  become_user: "{{ users[0] }}"
  command: "yay -S corrupter-git --noconfirm"
  when: ansible_distribution == "Archlinux"

- name: copy custome scripts
  copy:
    src: "{{ item.src }}"
    dest: "{{ homedir }}{{ item.dest }}"
    owner: "{{ users[0] }}"
    group: "{{ users[0] }}"
    mode: 0644
  with_items:
    - { src: 'todo.sh', dest: '.config/scripts/todo.sh' }
    - { src: 'setbg.sh', dest: '.config/scripts/setbg.sh' }

- name: copy wallpapers
  copy:
    src: "wallpaper/"
    dest: "{{ homedir }}.config/wallpapers/"
    owner: "{{ users[0] }}"
    group: "{{ users[0] }}"
    mode: 0600

# config dmenu / rofi
