# Load distro-specific variables
# - include_vars: "{{ ansible_distribution }}.yml"
#   tags: always

- block:
  - import_tasks: secure.yml
  - import_tasks: programs.yml
  - import_tasks: users.yml
  - import_tasks: AUR_programs.yml
    # - GUI.yml
    # - other.yml
