- name: install arch specific software
  package:
    name:
      # Shell
      - python-pywal
      - htop
      - zsh
      - zsh-syntax-highlighting
      - vim
      - bat
      - ranger
      - cmus
      - cmatrix
      - w3m
      - neofetch
      - powertop
      - youtube-dl
      - sudo
      - dmenu
      - fail2ban
      - powerline
      - powerline-fonts
      - powerline-vim
      - zsh-syntax-highlighting
      # Security
      - nmap
      - ufw
      - shellharden
      # Graphical
      - atom
      - flameshot   # look into better solutions
      - rofi
      - gnome-terminal # look into better solutions
      - firefox
      - signal-desktop
      - ttf-hack
      # - containerd  (look into configuring this first)
  when: ansible_distribution == "Archlinux"

- name: debian specific software
  package:
    name:
      # Shell
      - htop
      - zsh
      - zsh-syntax-highlighting
      - vim
      - bat
      - ranger
      - cmus
      - cmatrix
      - w3m
      - neofetch
      - powertop
      - youtube-dl
      - sudo
      - dmenu
      - fail2ban
      - zsh-syntax-highlighting
      # Security
      - nmap
      - ufw
      # - shellharden
      # Graphical
      - flameshot   # look into better solutions
      - rofi
      - gnome-terminal # look into better solutions
      - firefox
      - fonts-hack-ttf
      # - containerd  (look into configuring this first)
      # - atom
      # - python-pywal
      # - signal-desktop (https://itsfoss.com/install-signal-ubuntu/)
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: install yay on arch
  become_user: "{{ users[0] }}"
  command: "{{ item }}"
  with_items:
    - "cd ~/repo"
    - "git clone https://aur.archlinux.org/yay.git"
    - "cd yay"
    - "makepkg -si"
  when: ansible_distribution == "Archlinux"
  ignore_errors: true

# add packages w/ "yay -S pkg --noconfirm"
# remove packages w/ "yay -Rns pkg --noconfirm"
# clean unwanted dependencies w/ "ysy -Yc --noconfirm"

- name: install oh-my-zsh and related customizations
  become_user: "{{ users[0] }}"
  shell: 
    cmd: "{{ item }}"
  with_items:
    - "curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
    - "git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/custom/themes/powerlevel10k"
  ignore_errors: true

