- name: install arch specific software
  package:
    name:
      # Shell
      - python-pywal
      - htop
      - zsh
      - zsh-syntax-highlighting
      - vim
      - bat
      - ranger
      - cmus
      - cmatrix
      - w3m
      - neofetch
      - powertop
      - youtube-dl
      - sudo
      # Security
      - nmap
      - ufw
      - shellharden
      # Graphical
      - atom
      - flameshot   # look into better solutions
      - rofi
      - gnome-terminal # look into better solutions
      - firefox
      # - containerd  (look into configuring this first)
  when: ansible_distribution == "Archlinux"

- name: ubuntu specific software
  package:
    name:
      # Shell
      - htop
      - zsh
      - zsh-syntax-highlighting
      - vim
      - bat
      - ranger
      - cmus
      - cmatrix
      - w3m
      - neofetch
      - powertop
      - youtube-dl
      - sudo
      # Security
      - nmap
      - ufw
      # - shellharden
      # Graphical
      - flameshot   # look into better solutions
      - rofi
      - gnome-terminal # look into better solutions
      - firefox
      # - containerd  (look into configuring this first)
      # - atom
      # - python-pywal
  when: ansible_distribution in ["Debian", "Ubuntu"]


- name: install yay on arch
  become_user: "{{ users[0] }}"
  command: "{{ item }}"
  with_items:
    - "git clone https://aur.archlinux.org/yay-git.git"
    - "sudo systemctl enable ly.service"
  when: ansible_distribution == "Archlinux"
