- name: install shell programs
  package:
    name:
      - htop
      - zsh
      - zsh-syntax-highlighting
      - vim
      - bat #add alias to .zsh
      - ranger
      - cmus
      - cmatrix
      - w3m
      - neofetch
      - powertop
      - youtube-dl
      - sudo

- name: install security software
  package:
    name:
      - nmap
      - ufw

- name: install GUI software
  package:
    name:
      - flameshot   # look into better solutions
      - rofi
#      - containerd  (look into configuring this first)

- name: install arch specific software
  package:
    name:
      # Shell
      - python-pywal
      # Security
      - shellharden
      # GUI
      - atom
      - firefox
  when: ansible_distribution == "Archlinux"

# need to figure out how to install these specifics
# - name: ubuntu specific software
#   package:
#     name:
#       - atom
#       - shellharden
#       - python-pywal
