- name: create group
  group:
    name: "{{ item }}"
    state: present
  loop: "{{ users }}"

- name: create user
  user:
    name: "{{ item }}"
    group: "{{ item }}"
    groups: users,sudo
    state: present
    shell: /bin/zsh
    password: "{{ password1 }}" # set the password at the end so that sudo doesn't prompt when using become
  loop: "{{ users }}"

- name: create config directories
  file:
    path: "{{ homedir }}{{ item.dir }}"
    state: directory
    owner: "{{ users[0] }}"
    group: "{{ users[0] }}"
    mode: 0700
  with_items:
    - { dir: '.config' }
    - { dir: '.config/i3'}
    - { dir: '.zsh' }
    - { dir: 'repo' }

- name: copy dotfiles
  copy:
    src: "{{ item.src }}"
    dest: "{{ homedir }}{{ item.dest }}"
    owner: "{{ users[0] }}"
    group: "{{ users[0] }}"
    mode: 0600
  with_items:
    - { src: 'i3_config', dest: '.config/i3/config'}
    - { src: 'zshrc', dest: '.zshrc' }
    # - { src: 'bash/profile', dest: '.profile' }
    # - { src: 'vim/vimrc', dest: '.vimrc' }

# - name: copy individual zsh config files
#   copy:
#     src: users/{{ users[0] }}/zsh/{{ item.src }}
#     dest: {{ homedir }}/.zsh/{{ item.src }}
#     owner: {{ users[0] }}
#     group: {{ users[0] }}
#     mode: 0600
#   with_items:
#     - { src: 'aliases.zsh' }
#     - { src: 'bindkey.zsh' }
#     - { src: 'completion.zsh' }
#     - { src: 'exports.zsh' }
#     - { src: 'functions.zsh' }
#     - { src: 'history.zsh' }
#     - { src: 'path.zsh' }
#     - { src: 'plugins.zsh' }
#     - { src: 'prompt.zsh' }
#     - { src: 'setopt.zsh' }
#     - { src: 'theming.zsh' }

# - name: copy vim color files
#   copy:
#     src: users/{{ users[0] }}/vim/{{ item.src }}
#     dest: {{ homedir }}/.vim/colors/{{ item.src }}
#     owner: {{ users[0] }}
#     group: {{ users[0] }}
#     mode: 0600
#   with_items:
#     - { src: 'bubblegum-256-dark.vim' }
#     - { src: 'darktango.vim' }
#     - { src: 'jellybeans.vim' }
#     - { src: 'xoria256.vim' }
#     - { src: 'zenburn.vim' }

# - name: checkout git repositories
#   become: yes
#   git:
#     repo: "{{ item.repo }}"
#     dest: "{{ item.dest }}"
#     force: yes
#   with_items:
#     - { repo: 'https://github.com/ctrlpvim/ctrlp.vim.git', dest: '{{ homedir }}/.vim/bundle/ctrlp.vim' }
#     - { repo: 'https://github.com/davidhalter/jedi-vim.git', dest: '{{ homedir }}/.vim/bundle/jedi-vim' }
#     - { repo: 'https://github.com/pearofducks/ansible-vim', dest: '{{ homedir }}/.vim/bundle/ansible-vim' }
#     - { repo: 'https://github.com/rhysd/vim-grammarous.git', dest: '{{ homedir }}/.vim/bundle/vim-grammarous' }
#     - { repo: 'https://github.com/ron89/thesaurus_query.vim', dest: '{{ homedir }}/.vim/bundle/thesaurus_query' }
#     - { repo: 'https://github.com/scrooloose/nerdtree.git', dest: '{{ homedir }}/.vim/bundle/nerdtree' }
#     - { repo: 'https://github.com/tpope/vim-obsession.git', dest: '{{ homedir }}/.vim/bundle/vim-obsession' }
#     - { repo: 'https://github.com/vim-syntastic/syntastic.git', dest: '{{ homedir }}/.vim/bundle/syntastic' }
#   notify: update_vim_bundle_perms
